import React from "react";
// import { styled } from "@mui/material";
import Box from "@mui/material/Box";
// import Typography from "@mui/material/Typography";
// import Button from "@mui/material/Button";
import Grid from "@mui/material/Grid";
// import Paper from "@mui/material/Paper";
import Head from "next/head";
// import { makeStyles } from "@material-ui/core/styles";
import Card from "../Components/card";
// import Image from "next/image";
// import ProductImage from "../public/image/1000_F_128374324_37F3O5wRIgK0QfGt25KKRrbfMbPB96X2.jpeg";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import FeaturesCard from "../Components/FeaturesCard";

export default function Index() {
  const slider1 = "url(../public/image/slider2_1.jpeg)";
  // const item = styled(Paper)(({ theme }) => ({
  //   backgroundColor: "orange",
  //   ...theme.typography.body2,
  //   padding: theme.spacing(1),
  //   textAlign: "center",
  //   color: theme.palette.text.secondary,
  // }));

  return (
    <div>
      <Head>
        <title>Toria Spices</title>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container>
        {/* an image with bg and write up  */}

        <Box
          sx={{
            display: "flex",
            width: "100%",
            height: 400,
            backgroundImage: slider1,
            backgroundSize: "cover",
            backgroundRepeat: "no-repeat",
            backgroundPosition: "center",
            maxWidth: "100%",
            mx: "auto", // To center the box horizontally
            mt: 3,
          }}
        >
          <Grid container spacing={2}>
            <Box
              display="flex"
              // justifyContent="center"
              alignItems="center"
              width="100%"
              height={400}
              sx={{
                p: 5,
                color: "white",
                backgroundImage:
                  "url('https://images.unsplash.com/photo-1564149504298-00c351fd7f16?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80')",
                backgroundSize: "cover",
                backgroundPosition: "center",
              }}
            >
              {/* <p>Get the best outfit of your life</p> */}
              <h1>
                Finding the difference with <br /> ToriaSpices
              </h1>

              {/* <Button sx={{ background: "green", borderStartEndRadius: 20 }}>
                Shop now
              </Button> */}
            </Box>
          </Grid>
        </Box>
        {/* four cards with special attractive point  */}
        <Grid
          container
          spacing={2}
          justifyContent="center"
          alignItems="center"
          sx={{
            pt: 3,
            pb: 3,
          }}
        >
          <FeaturesCard />
          <FeaturesCard /> <FeaturesCard /> <FeaturesCard />
        </Grid>

        {/* our product with a filter */}
        <h2 sx={{ mx: "auto" }}>Our Product</h2>

        <Grid container spacing={2} sx={{ pt: 3, px: 3 }}>
          <Grid item xs={3}>
            <Card />
          </Grid>
          <Grid item xs={3}>
            <Card />
          </Grid>
          <Grid item xs={3}>
            <Card />
          </Grid>
          <Grid item xs={3}>
            <Card />
          </Grid>
        </Grid>
        {/* CTA with two cards */}

        {/* News letter */}

        {/* Testimonial */}

        {/* latest blog */}

        {/* brands that buy our product */}
      </Grid>

      {/* <Grid container>
     
        <Grid item sx={{ p: 5 }} xs={12} sm={8} md={6} lg={6}>
          <Typography variant="p">Product 2</Typography>
          <Typography variant="h4">Ginger</Typography>
          <Typography>
            “If you are going to use a passage of Lorem Ipsum, you need to be
            sure there isn't anything embarrassing hidden in the middle of text.
          </Typography>
        </Grid>
        <Grid item sx={{ p: 5, m: 5 }} xs={12} sm={8} md={4} lg={4}>
          <Card />
        </Grid>
      </Grid> */}
      {/* <Grid container>
        <Grid
          item
          sx={{ justify: "center", ml: "auto", mr: "auto", p: 5 }}
          xs={12}
          sm={12}
          md={12}
          lg={12}
        ></Grid>
        <Grid
          item
          sx={{ p: 5, m: 5 }}
          xs={12}
          sm={8}
          md={4}
          lg={4}
          // className="shade"
        >
          <Card />
        </Grid>
        <Grid item sx={{ p: 5 }} xs={12} sm={8} md={6} lg={6}>
          <Typography variant="p">Product 3</Typography>
          <Typography variant="h4"> Star Anise</Typography>
          <Typography>
            “If you are going to use a passage of Lorem Ipsum, you need to be
            sure there isn't anything embarrassing hidden in the middle of text.
          </Typography>
        </Grid>
      </Grid> */}
      {/* <Grid container display="colomn" sx={{ p: 3, justifyContent: "center" }}>
        <Grid item xs={12} sm={10} md={10} lg={10}>
          <Typography
            variant="h3"
            justify="center"
            backgroundColor="orange"
            color="white"
          >
            some of our trusted clients
          </Typography>
        </Grid>
        <Grid item xs={12} sm={6} md={3} lg={3}>
          <Typography variant="h3" justify="center">
            [Google logo]
          </Typography>
        </Grid>
        <Grid item xs={12} sm={6} md={3} lg={3}>
          <Typography variant="h3" justify="center">
            [Amazon logo]
          </Typography>
        </Grid>
        <Grid item xs={12} sm={6} md={3} lg={3}>
          <Typography variant="h3" justify="center">
            [Microsoft logo]
          </Typography>
        </Grid>
        <Grid item xs={12} sm={6} md={3} lg={3}>
          <Typography variant="h3" justify="center">
            [Codehouze Logo]
          </Typography>
        </Grid>
      </Grid> */}
      {/* <Grid container>
        <Grid
          item
          sx={{ justify: "center", ml: "auto", mr: "auto", p: 5 }}
          xs={12}
          sm={12}
          md={12}
          lg={12}
        >
          <Typography variant="h3">Customer Story</Typography>
        </Grid>
        <Grid item sx={{ p: 5 }} xs={12} sm={8} md={6} lg={6}>
          <Typography variant="p">Customer Story</Typography>
          <Typography variant="h4">Customer Story</Typography>
          <Typography>
            “If you are going to use a passage of Lorem Ipsum, you need to be
            sure there isn't anything embarrassing hidden in the middle of text.
          </Typography>
        </Grid>
        <Grid
          item
          sx={{ p: 5, m: 5 }}
          xs={12}
          sm={8}
          md={4}
          lg={4}
          className="shade"
        >
          <Card />
        </Grid>
      </Grid> */}
      {/* <Grid container>
        <Grid item lg={2} md={2} xs={2} sm={2}>
          <Grid
            item
            xs={8}
            sm={8}
            lg={8}
            sx={{ p: 5, mt: 5, backgroundColor: "orange", borderRadius: 5 }}
          >
            <Grid item justifyContent={"center"} xs={8} md={4} sm={8} lg={4}>
              <Typography
                variant="h5"
                component="h5"
                color="brown"
                borderColor="orange"
                fontSize="10"
                justify="left"
              >
                Enough talk, let's make you healthier
              </Typography>
            </Grid>
            <Grid
              item
              xs={8}
              md={4}
              sm={8}
              lg={4}
              sx={{ justifyContent: "right" }}
            >
              <Grid>
                <Image src={ProductImage} alt="CTA" width={50} height={20} />
              </Grid>
              <Button>Let Start</Button>
            </Grid>
          </Grid>
          <Grid item lg={2} md={2} sm={2} xs={2} />
        </Grid>
      </Grid> */}
    </div>
  );
}
