import React from "react";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Grid from "@mui/material/Grid";
import Typography from "@mui/material/Typography";
import Head from "next/head";
import Card from "../Components/ProductCard";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import FeaturesCard from "../Components/FeaturesCard";
import Link from "next/link";
import InputBase from "@mui/material/InputBase";
import ProductFilter from "../Components/ProductFilter";
import EmailIcon from "@mui/icons-material/Email";
import { BorderAllRounded } from "@material-ui/icons";
import { Paper } from "@mui/material";

export default function Index() {
  const slider1 = "url(../public/image/slider2_1.jpeg)";

  return (
    <Paper>
      <Head>
        <title>Toria Spices</title>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container>
        {/* an image with bg and write up  */}

        <Box
          sx={{
            display: "flex",
            width: "100%",
            height: 600,
            backgroundImage: slider1,
            backgroundSize: "cover",
            backgroundRepeat: "no-repeat",
            backgroundPosition: "center",
            maxWidth: "100%",
            mx: "auto", // To center the box horizontally
            mt: 3,
          }}
        >
          <Grid container spacing={2}>
            <Box
              display="flex"
              // justifyContent="center"
              alignItems="center"
              width="100%"
              height={600}
              sx={{
                p: 5,
                color: "white",
                backgroundImage:
                  "url('https://images.unsplash.com/photo-1564149504298-00c351fd7f16?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80')",
                backgroundSize: "cover",
                backgroundPosition: "center",
              }}
            >
              {/* <p>Get the best outfit of your life</p> */}
              <h1>
                Finding the difference with <br /> ToriaSpices
              </h1>

              <Button sx={{ background: "green", borderStartEndRadius: 20 }}>
                Shop now
              </Button>
            </Box>
          </Grid>
        </Box>
        {/* four cards with special attractive point  */}
        <Grid
          container
          spacing={2}
          justifyContent="center"
          // alignItems="center"
          sx={{
            pt: 3,
            pb: 3,
          }}
        >
          <Grid item xs={6} lg={2} md={2} sm={6}>
            <FeaturesCard />
          </Grid>
          <Grid item xs={6} lg={2} md={2} sm={6}>
            <FeaturesCard />
          </Grid>
          <Grid item xs={6} lg={2} md={2} sm={6}>
            <FeaturesCard />
          </Grid>
          <Grid item xs={6} lg={2} md={2} sm={6}>
            <FeaturesCard />
          </Grid>
        </Grid>

        {/* our product with a filter */}
        <Grid alignItems="center" sx={{ mx: "auto", fontSize: 20 }}>
          <h2>Our Products</h2>
        </Grid>

        <ProductFilter />
        <Grid container spacing={2} sx={{ pt: 3, px: 3 }}>
          <Grid item md={2} xs={6}>
            <Card />
          </Grid>
          <Grid item md={2} xs={6}>
            <Card />
          </Grid>
          <Grid item md={2} xs={6}>
            <Card />
          </Grid>
          <Grid item md={2} xs={6}>
            <Card />
          </Grid>
          <Grid item md={2} xs={6}>
            <Card />
          </Grid>
          <Grid item md={2} xs={6}>
            <Card />
          </Grid>
        </Grid>

        {/* CTA with two cards */}
        <Grid
          container
          spacing={1}
          alignItems="center"
          justifyContent="center"
          md={10}
          sx={{
            mx: "auto",
            px: "auto",
            // p: 5,
          }}
        >
          <Grid
            item
            md={5}
            xs={10}
            alignItems="center"
            position="relative"
            height={400}
            sx={{
              backgroundImage:
                "url('https://media.istockphoto.com/id/873964916/photo/spices-on-white-background-isolated-with-place-for-text.jpg?s=1024x1024&w=is&k=20&c=blGNr4E3vCUX1orCuQlOiP2ZTaExAECIDWvdyHa_X8w=')",
              backgroundSize: "cover",
              backgroundPosition: "center",
              mx: 3,
              mt: 5,
              borderRadius: 5,
            }}
          >
            <Box position="absolute" top={200} left={40}>
              <h2>THE QUALITY</h2>
              <p>MADE SPICE</p>
              <Button
                sx={{
                  color: "white",
                  background: "orange",
                  borderRadius: 10,
                  mx: 1,
                  px: 2,
                  "&:hover": {
                    backgroundColor: "black",
                    color: "white",
                  },
                }}
              >
                Shop Now
              </Button>
            </Box>
          </Grid>
          <Grid
            item
            height={400}
            md={5}
            xs={10}
            position="relative"
            sx={{
              p: 5,
              color: "black",

              backgroundImage:
                "url('https://as1.ftcdn.net/v2/jpg/04/87/96/38/1000_F_487963899_wpAa0pW71FK5eoWgIFjywVhFoZhnhZr7.jpg')",
              backgroundSize: "cover",
              backgroundPosition: "center",
              mx: 3,
              mt: 5,
              borderRadius: 5,
            }}
          >
            <Box position="absolute" top={200} left={400} sx={{}}>
              <h2>Discover Our</h2>
              <p>NEW RECIPES</p>
              <Button
                sx={{
                  color: "white",
                  background: "orange",
                  borderRadius: 10,
                  mx: 1,
                  px: 2,
                  "&:hover": {
                    backgroundColor: "black",
                    color: "white",
                  },
                }}
              >
                Shop Now
              </Button>
            </Box>
          </Grid>
        </Grid>
        {/* News letter */}
        <Grid
          container
          spacing={1}
          alignItems="center"
          // justifyContent="center"
          md={9}
          xs={10}
          sx={{
            mx: "auto",
            px: "auto",
            mt: 5,
            p: 10,
            background: "lightgrey",
            borderRadius: 3,
          }}
        >
          <Grid item display="flex" xs={6} md={6}>
            <Box
              display="flex"
              alignItems="center"
              justifyContent="center"
              flexDirection="column"
              xs={4}
              sx={{
                backgroundColor: "orange",
                color: "white",
                borderRadius: "100%",
                p: 3,
              }}
            >
              <EmailIcon fontSize="large" />
            </Box>
            <Box>
              <Typography variant="h3" sx={{ px: 1 }}>
                Newsletter
              </Typography>

              <div>
                <Typography variant="body1" sx={{ px: 1 }}>
                  Stay updated with our latest news and promotions.
                </Typography>
              </div>
            </Box>
          </Grid>

          <Grid item xs={12} md={6}>
            <Box sx={{ pt: 2 }}>
              <InputBase
                sx={{
                  ml: 5,
                  flex: 10,
                  background: " white",
                  borderTopLeftRadius: 10,
                  borderBottomLeftRadius: 10,
                  px: 5,
                  p: 2,
                }}
                placeholder="Enter Your E-mail..."
                inputProps={{ "aria-label": "Enter Your E-mail..." }}
              />
              <Button
                sx={{
                  color: "white",
                  backgroundColor: "orange",
                  borderTopRightRadius: 10,
                  borderBottomRightRadius: 10,
                  p: 2,
                  pt: 1,
                  fontSize: 18,
                  "&:hover": {
                    backgroundColor: "black",
                    color: "white",
                  },
                }}
              >
                Subscribe
              </Button>
            </Box>
          </Grid>
        </Grid>

        {/* Testimonial */}
        <Grid container spacing={1}></Grid>

        <Grid container display="flex">
          {/* latest blog */}
          <Grid item>1</Grid>
          <Grid item>2</Grid>
          <Grid item>3</Grid>
        </Grid>

        <Grid container>
          {/* brands that buy our product */}
          Carocel
        </Grid>
      </Grid>
    </Paper>
  );
}
