import React from "react";
import { styled } from "@mui/material";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import Grid from "@mui/material/Grid";
// import styled from "@mui/material/styled";
import Paper from "@mui/material/Paper";
import Head from "next/head";
import { makeStyles } from "@material-ui/core/styles";
import Card from "../Components/card";
import Image from "next/image";

// import Image from "https://media.istockphoto.com/photos/various-spices-a-vintage-spoons-on-stone-table-colorful-herbal-and-picture-id1340677256"

export default function Index() {
  const Item = styled(Paper)(({ theme }) => ({
    backgroundColor: "orange",
    ...theme.typography.body2,
    padding: theme.spacing(1),
    textAlign: "center",
    color: theme.palette.text.secondary,
  }));

  // const useStyles = makeStyles((theme) => ({
  //   root: {
  //     backgroundColor: "white",
  //   },
  //   links: {
  //     color: "orange",
  //   },
  // }));

  // const classes = useStyles();
  return (
    <div>
      <Head>
        <title>Toria Spices</title>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid container>
        <Image
          src="/photos/variety-of-spices-on-kitchen-table-picture-id537710412"
          alt="slide image"
          width={100}
          height={20}
          marginBottom={15}
          layout="fill"
        />

        <Grid container>
          <Grid item sx={{ mt: 5, p: 2 }} lg={4} md={6} sm={6} />
          <Grid
            item
            sx={{ mt: 2, p: 2, backgroundColor: "orange" }}
            xs={12}
            sm={4}
            md={10}
            lg={8}
            className="bannerBadge1"
          >
            <Typography variant="h3" component="h4" color="white">
             Best Organic Products
            </Typography>
          </Grid>
          <Box
            xs={12}
            sm={12}
            md={10}
            lg={10}
            sx={{
              backgroundImage: `url("https://media.istockphoto.com/photos/various-spices-selection-picture-id480519448")`,
              p: 3,
              color: "orange",
              margin: 3,
            }}
          >
            <Typography
              variant="h6"
              component="h6"
              color="brown"
              borderColor="orange"
              fontSize="10"
              justify="center"
              backgroundColor="white"
              borderRadius={5}
              padding={2}
              margin={3}
            >
              Cooking made simple! Introducing Spice 'n Easy Recipe Mixes With
              Spice 'n Easy, cooking is as simple as 1, 2, 3!Just open, spice
              and serve. Each packet includes the pre-measured spices needed to
              make a quick, simple and tasty recipe with a few kitchen staples.
              Try recipes like our Curry blend or Yagi . No experience needed.
            </Typography>
            <Grid container>
              <Grid item sx={{ mt: 5, p: 2 }} lg={6} md={6} sm={6} />
              <Grid xs={6} sm={6} lg={6}>
                <Button
                  variant="contained"
                  color="primary"
                  size="large"
                  onClick={() => {
                    alert(
                      "More information about our Spice 'n Easy Recipe Mixes are coming soon here... "
                    );
                  }}
                >
                  Learn More
                </Button>
              </Grid>
            </Grid>
          </Box>

          <Grid item xs={12} sm={4} lg={4}>
            <Card />
          </Grid>
          <Grid item xs={12} sm={4} lg={4}>
            <Card />
          </Grid>
          <Grid item xs={12} sm={4} lg={4}>
            <Card />
          </Grid>
          <Grid item xs={12} sm={4} lg={4}>
            <Card />
          </Grid>
          <Grid item xs={12} sm={4} lg={4}>
            <Card />
          </Grid>
          <Grid item xs={12} sm={4} lg={4}>
            <Card />
          </Grid>
        </Grid>
      </Grid>
    </div>
  );
}
